custombucket = "mydevopsawsprojectbucket"
table = "intellipaat"
databasehost = "db-devopsaws-project.cr2ii33fqiqh.us-east-1.rds.amazonaws.com"
duser = "admin"
dpass = "admin123"
s3database = "intellipaat"
kapp = "http://10.0.149.50:31883/"
